# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = """
$localip[$username$hostname](bold)\
$directory\
$git_branch\
$git_state\
$git_status\
$battery\
$all\
$line_break\
$cmd_duration\
$shell $character\
"""

right_format = "$time"

[aws]
symbol = "îŒ½  "

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 25
style = "dimmed bold yellow"

[[battery.display]]
threshold = 50
style = "bold yellow"

[[battery.display]]
threshold = 75
style = "bold green"

[[battery.display]]
threshold = 100
style = "dimmed bold green"

[buf]
symbol = "ï’ "

[c]
symbol = "î˜ "

[character]
success_symbol = "[âœ](green) "
error_symbol = "[âœ](red) "

[cmd_duration]
format = "[$duration]($style) "
style = "bold bright-black"
show_milliseconds = true
min_time = 20

[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "

[docker_context]
symbol = "ïŒˆ "

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
read_only = " ï ½"
use_os_path_sep = false

[elixir]
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
symbol = "ï˜ "

[git_status]
format = """(\
[\
(\\[($conflicted$deleted$modified$renamed$staged)(218)\\])\
((\\($ahead_behind$stashed)\\))\
]($style)\
) """
style = "cyan"
conflicted = "c"
untracked = "u"
modified = "m"
staged = "s"
renamed = "r"
deleted = "d"
stashed = "â‰¡"

[golang]
symbol = "î˜§ "

[haskell]
symbol = "î· "

[hg_branch]
symbol = "ï˜ "

[hostname]
format = "@[$ssh_symbol$hostname]($style) "
style = "cyan dimmed bold"

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[localip]
format = "[$localipv4]($style) as "
style = "bold bright-black"
disabled = false

[memory_usage]
symbol = "ï¡š "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ï‹œ "

[nodejs]
symbol = "îœ˜ "

[package]
format = "[$symbol$version]($style) "
symbol = "ï£– "

[python]
symbol = "îˆµ "

[spack]
symbol = "ğŸ…¢ "

[time]
disabled = false
format = "at [$time]($style)"
style = "bold bright-black"

[rust]
symbol = "î¨ "

[shell]
disabled = false
format = "[$indicator]($style)"
style = "bold bright-black"

[username]
format = "[$user]($style)"
style_user = "cyan bold"
style_root = "green bold"
