# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# add_newline = false
format = """
[$username](bold)$localip$hostname \
$battery\
$git_branch\
$git_state\
$git_status\
$all\
$line_break\
$directory\
$shell $character\
"""

right_format = "$cmd_duration$time"

[aws]
symbol = "îŒ½  "

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 25
style = "dimmed bold yellow"

[[battery.display]]
threshold = 50
style = "bold yellow"

[[battery.display]]
threshold = 75
style = "bold green"

[[battery.display]]
threshold = 100
style = "dimmed bold green"

[buf]
symbol = "ï’ "

[c]
symbol = "î˜ "

[character]
success_symbol = "[#](bold green) "
error_symbol = "[#](bold red) "

[cmd_duration]
format = "[$duration]($style) "
style = "bold bright-black"
show_milliseconds = true
min_time = 20

[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "

[docker_context]
symbol = "ïŒˆ "

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
read_only = " ï ½"
use_os_path_sep = false

[elixir]
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
symbol = "îœ¥ "

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\):'

[git_status]
format = """(\
[\
(\\[($conflicted$deleted$modified$renamed$staged)(218)\\])\
((\\($ahead_behind$stashed)\\))\
]($style)\
) """
style = "cyan"
conflicted = "c"
untracked = "u"
modified = "m"
staged = "s"
renamed = "r"
deleted = "d"
stashed = "â‰¡"

[golang]
symbol = "î˜§ "

[haskell]
symbol = "î· "

[hg_branch]
symbol = "ï˜ "

[hostname]
format = '[\($ssh_symbol$hostname\)]($style)'
style = "cyan dimmed bold"
ssh_only = false

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[localip]
format = "@[$localipv4]($style)"
style = "bold bright-black"
ssh_only = false
disabled = false

[memory_usage]
symbol = "ï¡š "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ï‹œ "

[nodejs]
symbol = "îœ˜ "

[package]
format = "[$symbol$version]($style) "
symbol = "ï£– "

[python]
symbol = "îˆµ "

[spack]
symbol = "ğŸ…¢ "

[time]
disabled = false
format = "[$time]($style)"
style = "bold bright-black"

[rust]
symbol = "î¨ "

[shell]
disabled = false
format = "[$indicator]($style)"
style = "bold bright-black"

[username]
format = "[$user]($style)"
show_always = true
style_user = "cyan bold"
style_root = "green bold"
