[[language]]
name = "bash"

[[language]]
name = "c"

[[language]]
name = "cpp"

[[language]]
name = "cmake"

[[language]]
name = "css"

[[language]]
name = "dockerfile"

[[language]]
name = "go"

[[language]]
name = "html"

[[language]]
name = "javascript"

[[language]]
name = "json"

[[language]]
name = "jsx"

[[language]]
name = "lua"

[[language]]
name = "make"

[[language]]
name = "markdown"

[[language]]
name = "python"
language-id = "python"
roots = ["pyproject.toml", ".git", ".jj", ".venv/"]
language-servers = ["basedpyright", "ruff"]
auto-format = true
formatter = { command = "ruff", args = ["format", "-"] }
file-types = ["py", "ipynb"]
comment-token = "#"
shebangs = ["python"]

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "ruff"
args = ["server"]
environment = { "RUFF_TRACE" = "messages" }

[[language]]
name = "regex"

[[language]]
name = "rust"

[[language]]
name = "scss"

[[language]]
name = "sql"

[[language]]
name = "svelte"

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "tsx"

[[language]]
name = "typescript"

[[language]]
name = "yaml"
scope = "source.yaml"
file-types = ["yml", "yaml"]
roots = []
indent = { tab-width = 2, unit = "  " }
language-servers = ["yaml-language-server"]
injection-regex = "yml|yaml"

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
kubernetes = "/*.yaml"

[[language]]
name = "xml"
